In [1]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [52]:
import numpy as np

print(np.__version__)


1.26.4


In [53]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [54]:
listarray= np.array([[1,2,3],[5,4,6],[8, 9 ,10]])
listarray

array([[ 1,  2,  3],
       [ 5,  4,  6],
       [ 8,  9, 10]])

In [55]:

listarray.size

9

In [56]:
listarray.shape

(3, 3)

In [57]:
listarray.dtype

dtype('int64')

In [58]:
np.array({24,34,35})

array({24, 34, 35}, dtype=object)

In [59]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
rng = np.arange(9)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
lspace = np.linspace(1,100,10)
lspace

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [62]:
emp = np.empty((4,6))
emp

array([[0.10588235, 0.61960784, 0.46666667, 1.        , 0.85098039,
        0.37254902],
       [0.00784314, 1.        , 0.45882353, 0.43921569, 0.70196078,
        1.        ],
       [0.90588235, 0.16078431, 0.54117647, 1.        , 0.4       ,
        0.65098039],
       [0.11764706, 1.        , 0.90196078, 0.67058824, 0.00784314,
        1.        ]])

In [63]:
emp_like = np.empty_like(lspace)
emp_like

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [64]:
#Create a 5x5 identity matrix using NumPy.
ide = np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
ide.shape

(5, 5)

In [66]:
arr  = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
arr = arr.ravel()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
arr.shape

(9,)

In [70]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [71]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [72]:
ar.sum(axis=0)


array([12,  8,  9])

In [73]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [74]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [75]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [76]:
#Create a filter array that will return only values higher than 30:
arr = np.array((23,34,45,56,67))
filter_arr= []

for element in arr:
  if element  > 30:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, True, True, True, True]
[34 45 56 67]


In [9]:
import pandas as pd

In [10]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [13]:

df = pd.read_csv('data2.csv')

print(df) 

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


In [14]:
import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300


In [16]:
df = pd.read_csv('data2.csv')

print(df.head(10))

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0


In [17]:
print(df.info()) 


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB
None
